### ISSUE TITLE
Error should start from non-zero

### ISSUE THREAD

**Issue by XuJiandong** [APRO-Oracle/apro-ckb-contract#1]
The first error code(IndexOutOfBound) is with value zero:
https://github.com/APRO-Oracle/apro-ckb-contract/blob/ed6a352b05ad30809a1656ff73615a97bd2a19cc/contracts/contract/src/common/error.rs#L5

It returns zero as success when IndexOutOfBound occurs:
https://github.com/APRO-Oracle/apro-ckb-contract/blob/ed6a352b05ad30809a1656ff73615a97bd2a19cc/contracts/contract/src/main.rs#L36

**Comment by crypto009** [comment]
How about adding an item that is never used to occupy `errcode 0`, like this:
```
pub enum Error {
    SkipCode0,   // ensure this item would never be used 
    IndexOutOfBound,
    LengthNotEnough,
    ItemMissing,
    ....
}
```

**Comment by XuJiandong** [comment]
use this 
```rust
pub enum Error {
    IndexOutOfBound = 1,
    LengthNotEnough,
    ItemMissing,
    ....
}
```

**Comment by XuJiandong** [comment]
use this
```rust
pub enum Error {
    IndexOutOfBound = 1,
    LengthNotEnough,
    ItemMissing,
    ....
}
```

**Comment by crypto009** [comment]
> use this
> 
> ```rust
> pub enum Error {
>     IndexOutOfBound = 1,
>     LengthNotEnough,
>     ItemMissing,
>     ....
> }
> ```

Good advice!
